kind: pipeline
type: docker
name: hello-world

steps:
- name: docker  
  image: plugins/docker
  settings:
    dockerfile: docker/Dockerfile
    registry: https://dockerproxy.cn
    repo: hnitro/test-drone-docker-hub
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: 
      - latest
